### ISSUE TITLE
Semantic of deleting/removing a ResourceContainer after transformation.

### ISSUE THREAD

**Issue by kjuli** [PalladioSimulator/Palladio-Analyzer-Slingshot-Extension-PCM-Core#28]
Currently, already scheduled jobs could be a problem when a resource container in which the jobs are scheduled is going to be deleted.

We have three option:

- cancel them with a 'JobCancelled`event + delete the active resource (no 'wrong' measurements)
- finish waiting jobs immediately + delete the active resource
- let waiting jobs finish on their own + delete the active resource once the queue is empty

for now, we wil pursue 3. because it's the least effort.

**Comment by klinakuf** [comment]
FK: Test and report until the 4.8.

**Comment by klinakuf** [comment]
Tested scaling in with two resource containers; measurements correctly reflect the increased load in the remaining unit container: 

![Image](https://github.com/PalladioSimulator/Palladio-Analyzer-Slingshot-Extension-PCM-Core/assets/1203153/930493d7-96c2-4248-9adc-3df3f5e6a895)
